---
apiVersion: v1
kind: Pod
metadata:
  name: adapter
spec:
  volumes:
  - name: sharedlogs
    emptyDir: {}
  containers:
  # 앱 컨테이 - 5s에 한번씩 /var/log/top.txt 파일에 로그 생성
  - name: app-container
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "while true; do date > /var/log/top.txt && top -n 1 -b >> /var/log/top.txt; sleep 5; done"]
    volumeMounts:
    - name: sharedlogs
      mountPath: /var/log
  # 어댑터 컨테이너 - top.txt 파일의 내용 가공-> /var/log/status.html 파일에 저장
  # 가공한 데이터 == MEM, CPU 사용량
  - name: adapter-container
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "while true; do (echo '<pre>' > /var/log/status.html) && \
          (cat /var/log/top.txt | head -1 >> /var/log/status.html) && \
          (cat /var/log/top.txt | grep '^Mem:' | awk -F, '{print $1}' >> /var/log/status.html) && \
          (cat /var/log/top.txt | grep '^CPU' | awk '{print $1, $8,$9}' >> /var/log/status.html) && \
          (echo '</pre>' >> /var/log/status.html); sleep 5; done"]
    volumeMounts:
    - name: sharedlogs
      mountPath: /var/log
  # 사이드카 컨테이너 - 공유된 볼륨의 내용을 웹에서 확인
  - name: sidecar-container
    image: nginx:1.14
    ports:
    - containerPort: 80
    volumeMounts:
    - name: sharedlogs
      mountPath: /usr/share/nginx/html
