apiVersion: v1
kind: Pod
metadata:
  name: genid-stone
spec:
  containers:
  - name: fakeid
    image: 9rrrrm/genid:env
    env:
    - name: INTERVAL
      valueFrom:
        configMapKeyRef:
          name: test-config
          key: INTERVAL
    - name: OPTION
      valueFrom:
        configMapKeyRef:
          name: test-config
          key: OPTION
    volumeMounts:
    - name: html
      mountPath: /webdata

  - name: web-server
    image: nginx:1.14
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80
  volumes:
  - name: html
    emptyDir: {}
