apiVersion: v1
kind: Service
metadata:
  name: rolling-svc
spec:
  # type: ClusterIP
  # cluseterIP: 10.100.10.10
  selector:
    app: web
    version: stable
  ports:
  - port: 80
    targetPort: 8080
