apiVersion: v1
kind: Service
metadata:
  name: blue-green-svc
spec:
  # type: ClusterIP
  # clusterIP: 10.100.10.10
  selector:
    app: web
    version: blue
  ports:
  - port: 80
    targetPort: 8080
