apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: bc5a00d1701e1a91380eee2935f53a63a5a783f76b0561b15a3ba88f08fadf2b
    cni.projectcalico.org/podIP: 172.16.11.86/32
    cni.projectcalico.org/podIPs: 172.16.11.86/32
  creationTimestamp: "2024-12-15T12:23:40Z"
  labels:
    run: testpod
  name: testpod
  namespace: default
  resourceVersion: "454432"
  uid: 9b33e154-b9d8-476f-bffa-79646baaf962
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: testpod
    ports:
    - containerPort: 80
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-92kng
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: regcred
  nodeName: node1.example.com
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: pod-viewer
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-92kng
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-12-15T12:23:48Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2024-12-15T12:23:41Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-12-15T12:23:48Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-12-15T12:23:48Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-12-15T12:23:41Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://2a994c529009fae6a9d7f0e5d1e97806d2fd67ad571c00ac60171a081fb8c79b
    image: docker.io/library/nginx:latest
    imageID: docker.io/library/nginx@sha256:fb197595ebe76b9c0c14ab68159fd3c08bd067ec62300583543f0ebda353b5be
    lastState: {}
    name: testpod
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-12-15T12:23:47Z"
  hostIP: 192.168.10.11
  hostIPs:
  - ip: 192.168.10.11
  phase: Running
  podIP: 172.16.11.86
  podIPs:
  - ip: 172.16.11.86
  qosClass: BestEffort
  startTime: "2024-12-15T12:23:41Z"
